all: challenge1 challenge2 challenge3

challenge1:
	gcc -c challenge1.c
	gcc challenge1.o -o challenge1

challenge2:
	gcc -c challenge2.c
	gcc challenge2.o -o challenge2

challenge3:
	gcc -c challenge3.c
	gcc challenge3.o -o challenge3 -lm

clean:
	rm -f challenge1 challenge2 challenge3 *.o

